### ISSUE TITLE
Incompatible database options

### ISSUE THREAD

**Issue by kamino** [quarkslab/irma-common#3]
@guillaumededrie, @ch0k0bn, I have a problem with [this commit](https://github.com/quarkslab/irma-common/blob/39c2fbe1cb46765142fa42a6e84eb16bca72584e/irma/database/sqlhandler.py#L61) with an already provisioned frontend. If the database does not use UTF-8 from the beginning, the ``frontend_app`` cannot start and fails with a database connection error.

What do you suggest ? We should planify to add a migration script ? FYI, at the moment, this code is not used in any repository (version is forced by submodules). Thus, this is not at all a P1 issue, as far as no body need to display and store files with utf8 special characters in their database.

**Comment by guillaumededrie** [comment]
I think the migration script is needed indeed. We should consider using https://bitbucket.org/zzzeek/alembic or another migration system for SQLAlchemy, and integrate this modification as the first migration.

**Comment by guillaumededrie** [comment]
Hi @kamino,
Can we close the issue (see there for migration implementation: https://github.com/quarkslab/irma-frontend/pull/73).

Regards.

**Comment by kamino** [comment]
@guillaumededrie I have not tested the futher changes on irma-common, but I think the problem with utf-8 is not yet solved. @Leereen has an answer the answer, maybe ? 

@Leereen is the database initialized by default with utf-8 support ?

**Comment by ch0k0bn** [comment]
support of utf8 is now fully handled server side ( https://github.com/quarkslab/irma-ansible/commit/98f05ce28262f1f1bc89e6af00d98de785db0988 )
